[config]
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true

[env]
CARGO_MAKE_WORKSPACE_EMULATION = true
CARGO_MAKE_CRATE_WORKSPACE_MEMBERS = ["./crates/api", "./crates/sendmail"]

[tasks.default]
alias = "dev"

[tasks.format-check]
command = "cargo"
args = ["fmt", "--all", "--check"]

[tasks.clippy]
env = { RUSTFLAGS = "-Dwarnings" }
command = "cargo"
args = ["clippy"]

[tasks.check]
dependencies = ["format-check", "clippy"]

[tasks.init]
dependencies = ["init-nix", "init-npx"]

[tasks.init-nix]
condition.env_true = ["IN_NIX_SHELL"]
script.pre = "wrangler d1 create mail-subscriptions"
script.main = "wrangler d1 apply mail-subscriptions"
script.post = "echo 'Your Database has created with name: mail-subscriptions'"

[tasks.init-npx]
condition.env_false = ["IN_NIX_SHELL"]
script.pre = "npx wrangler d1 create mail-subscriptions"
script.main = "npx wrangler d1 migrations apply mail-subscriptions"
script.post = "echo 'Your Database has created with name: mail-subscriptions'"

[tasks.migration-new]
command = "wrangler"
args = ["d1", "migrations", "create", "mail-subscriptions"]

[tasks.migration-apply]
command = "wrangler"
args = ["d1", "migrations", "apply", "mail-subscriptions"]

[tasks.dev]
dependencies = ["run-api", "run-sendmail"]
