name = "newletter-sendmail"
workers_dev = true
main = "build/worker/shim.mjs"
compatibility_date = "2025-06-10"

[placement]
mode = "smart"

[observability]
enabled = true

[build]
command = "worker-build --release"

[[d1_databases]]
binding = "DB"
database_name = "mail-subscriptions"
# Replace this if is needed
database_id = "e75396da-6153-4389-b66b-bbee37496832"

[[rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
fallthrough = false

# Docs: https://developers.cloudflare.com/workers/configuration/environment-variables/
[env.local.vars]
