name = "newletter-api"
workers_dev = true
main = "build/worker/shim.mjs"
compatibility_date = "2024-03-14"

# Docs: https://developers.cloudflare.com/workers/configuration/routing/routes/
# routes = [
#     { pattern = "subdomain.example.com/*", zone_name = "example.com" },
# ]

[build]
command = "worker-build --release"

[[d1_databases]]
binding = "DB"
database_name = "mail-subscriptions"
# Replace this if is needed
database_id = "e75396da-6153-4389-b66b-bbee37496832"

[[rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
fallthrough = false

# Docs: https://developers.cloudflare.com/workers/configuration/environment-variables/
[env.local.vars]
