name: Deploy to production

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy.yml"
      - "crates/**/wrangler.toml"
      - "crates/**/src/**/**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain.toml"

jobs:
  quality-gate:
    uses: ./.github/workflows/quality-gate.yml
    with:
      checks-command: "--all --check"
      clippy-command: "-- -D warnings"
      tests-command: "test"

  deploy:
    needs: [quality-gate]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install nix
        uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true

      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: build-${{ runner.os }}-${{ hashFiles('**/*.nix', 'flake.lock') }}
          restore-prefixes-first-match: build-${{ runner.os }}-

      - name: Build both workers
        run: nix build

      - name: Fix up wrangler toml
        run: |

          fix-up () {
            echo "---- Before"
            cat crates/$1/wrangler.toml
            
            cat crates/$1/wrangler.toml | sed "s/main = \"build/main = \"result\/$1/" | sed 's/command = "worker-build --release"/command = "echo dummy build"/' >| crates/$1/wrangler.prod.toml
            
            echo "---- After"
            cat crates/$1/wrangler.prod.toml
          }

          echo "----- API -----"
          fix-up api

          echo "----- SENDMAIL -----"
          fix-up sendmail

      - name: Clone result
        run: |
          cp -r result crates/api/result
          cp -r result crates/sendmail/result

      - name: Deploy API
        uses: cloudflare/wrangler-action@v3
        # env:
          # YOUR_SECRET: ${{ secrets.YOUR_SECRET }}
          # YOUR_OTHER_SECRET: ${{ secrets.YOUR_OTHER_SECRET }}
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "crates/api"
          command: deploy -c wrangler.prod.toml
          # secrets: |
          #   YOUR_SECRET
          #   YOUR_OTHER_SECRET

      - name: Deploy Sendmail
        uses: cloudflare/wrangler-action@v3
        # env:
          # YOUR_SECRET: ${{ secrets.YOUR_SECRET }}
          # YOUR_OTHER_SECRET: ${{ secrets.YOUR_OTHER_SECRET }}
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "crates/sendmail"
          command: deploy -c wrangler.prod.toml
          # secrets: |
          #   YOUR_SECRET
          #   YOUR_OTHER_SECRET
